### ISSUE TITLE
流量不准确是怎么回事？

### ISSUE THREAD

**Issue by chenwdong** [zls0424/ngx_req_status#10]
我用这个插件来统计hls流量，发现每个ts文件的流量都是原始文件大小的16倍，请问是什么原因？

**Comment by chenwdong** [comment]
是不是因为这个流量是小b，而且包含了上下行，所以有了16倍这个数字，我这样理解可以吗

**Comment by zls0424** [comment]
上下行这个可能是包含了内部跳转, 应该算是不太合理.

**Comment by chenwdong** [comment]
那这个数值怎么理解？1.确定是包含上下行。2.是小b。     还有这个数值现在用起来是不准确的是吗？

**Comment by chenwdong** [comment]
内部跳转有request这个字段可以进行相应的计算，这个是没所谓的，关键在于没有内部跳转的时候，这个数值的来源是否可靠，包含了哪些流量。（多谢答复）

**Comment by zls0424** [comment]
统计的是这个请求上所有写出的数据, 上下行这个按说不应该, 你可以贴下 nginx 配置的示例代码

**Comment by chenwdong** [comment]
![image](https://user-images.githubusercontent.com/26000773/29554200-d2a974f8-8750-11e7-9bcc-c7084f2a83f9.png)
![image](https://user-images.githubusercontent.com/26000773/29554215-e05e5c62-8750-11e7-8cc3-afa62b2e330e.png)

**Comment by zls0424** [comment]
你的 include 里包含对这个请求的处理么? qq 讨论吧
