### ISSUE TITLE
在1.4/1.6版本下编译make时都报这个错怎么解决。

### ISSUE THREAD

**Issue by R1hug0** [zls0424/ngx_req_status#3]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
                -o objs/ngx_modules.o \
                objs/ngx_modules.c
./ngx_req_status-master/ngx_http_req_status_module.c: In function ‘ngx_http_req_status_handler’:
./ngx_req_status-master/ngx_http_req_status_module.c:306:41: error: variable ‘tp’ set but not used [-Werror=unused-but-set-variable]
     ngx_time_t                         *tp;

**Comment by zls0424** [comment]
Please try the latest version

**Comment by R1hug0** [comment]
tks  ,it already sloved.
