### ISSUE TITLE
请问这个错误是怎么回事？

### ISSUE THREAD

**Issue by tianxiaguixin** [zls0424/ngx_req_status#4]
服务器：CentOS release 6.7 (Final)
make -f objs/Makefile
make[1]: Entering directory `/root/nginx-1.8.0'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/ngx_req_status-master/ngx_http_req_status_module.o \
        ../ngx_req_status-master//ngx_http_req_status_module.c
../ngx_req_status-master//ngx_http_req_status_module.c: In function ‘ngx_http_req_status_init’:
../ngx_req_status-master//ngx_http_req_status_module.c:1035: error: ‘ngx_http_top_write_filter’ undeclared (first use in this function)
../ngx_req_status-master//ngx_http_req_status_module.c:1035: error: (Each undeclared identifier is reported only once
../ngx_req_status-master//ngx_http_req_status_module.c:1035: error: for each function it appears in.)
make[1]: *** [objs/addon/ngx_req_status-master/ngx_http_req_status_module.o] Error 1
make[1]: Leaving directory`/root/nginx-1.8.0'
make: **\* [build] Error 2

**Comment by zls0424** [comment]
编译前打过 patch 么?

**Comment by leon0908** [comment]
楼主解决了么。。我也遇到了。。patch打过了，但make的时候还是报这个
open resty版本1.11.2.5
nginx版本1.11.2

**Comment by zls0424** [comment]
patch 打的是 write_filter-1.7.11.patch 么?

**Comment by yyzhou0811** [comment]
这个问题有解决方法吗

**Comment by leon0908** [comment]
我最后用了tengine的模块动态编译成功了，可以参考下使用这个https://github.com/gfrankliu/nginx-http-reqstat

**Comment by zzliliang199053** [comment]
请教，openresty-1.13.6.2 编译尝试加入该模块，打patch时会报错，应该如何解决呢

 patch -p1 < ../ngx_req_status/write_filter-1.7.11.patch 
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -pruN nginx-1.7.11/src/http/ngx_http.c nginx-1.7.11.zls/src/http/ngx_http.c
|--- nginx-1.7.11/src/http/ngx_http.c   2015-04-21 22:12:00.000000000 +0800
|+++ nginx-1.7.11.zls/src/http/ngx_http.c       2015-06-04 12:10:58.989314197 +0800
--------------------------
File to patch:
