### ISSUE TITLE
能对统计的信息字段做一个名词解释吗？

### ISSUE THREAD

**Issue by marksnoopy** [zls0424/ngx_req_status#5]
RT，下面有些字段不是很明白啥意思，能简单解释以下吗？

zone_name       key     max_active      max_bw  traffic requests        active  bandwidth

**Comment by zhengxiaochuan-3** [comment]
@marksnoopy

zone_name 
 你定义的zone名称 比如 server_addr
key 
 你定义的统计变量的名称 比如 127.0.0.1
max_active 
 最大并发数
max_bw 
 最大的传输带宽
traffic 
 总的传输量
requests 
 总的请求数
active 
 当前并发数
bandwidth
 当前传输带宽

**Comment by marksnoopy** [comment]
thx

**Comment by marksnoopy** [comment]
还有一个问题，这个带宽是上行还是下行，还是总带宽？

**Comment by zhengxiaochuan-3** [comment]
下行

**Comment by zls0424** [comment]
感谢 @zhengxiaochuan-3 帮忙解答
