### ISSUE TITLE
为什么我装好了之后显示信息格式并不是demo那样的..

### ISSUE THREAD

**Issue by bao451326803** [zls0424/ngx_req_status#6]
都是类似这种的
localhost,25380,16074,1,54,54,0,0,0,0,0,0,0,0,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
192.168.0.134,25380,16074,1,54,54,0,0,0,0,0,0,0,0,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Comment by zls0424** [comment]
贴一下配置?

**Comment by bao451326803** [comment]
用的是tengine2.1.1 是nginx1.6.2的内核
req_status_zone server_name $server_name 256k;
req_status_zone server_addr $server_addr:$server_port 256k;

 location /req {
           allow 127.0.0.1;
           req_status_show;        --------------------这里还不能使用 on。。报错nginx: [emerg] zero size shared memory zone "on"
        }

感谢了....这个东东对我来所比较着急..

**Comment by bao451326803** [comment]
@zls0424   这个问题是我的疏忽...由于我使用的是tengine，它那玩意自带了这个模块，而且还是重写后的..导致了这个问题...还是感谢你了~

**Comment by zls0424** [comment]
好的

**Comment by boy461205160** [comment]
请问，tengine是不是不能使用ngx_req_status模块，
#nginx -t
the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] zero size shared memory zone "on"
configuration file /etc/nginx/nginx.conf test failed
请解答下，谢谢！

**Comment by zls0424** [comment]
@boy461205160 是的, 他们使用了冲突的指令名称
